### ISSUE TITLE
I can not reproduce the experimental results by using the .pt file in the pretrained folder. 

### ISSUE THREAD

**Issue by gaocrr** [RoyalSkye/Omni-VRP#1]
I load the .pt file from the pretrained/POMO-CVRP folder and achieve 12% gap on cvrp200_rotation which is much worse than the reported results.  Maybe the given .pt file is not the meta-trained model. For the convenience of reproduction, could you provide the meta-trained model that can reproduce the experimental results in the paper?

**Comment by RoyalSkye** [comment]
Hi, the .pt file is not the (meta-) pretrained model. It is the model pretrained on uniformly distributed data following the POMO source code. It is provided since the meta-training could also apply to the pretrained model. 

For reference, I have uploaded the meta-pretrained models at 50K and 250K iteration. I found them in my log files and did not check the results (but should be around ~2%). For fully reproduce the results, please run train.py.

**Comment by hanseul-jeong** [comment]
I just wanna check the specific model of pre-trained weights. is it correct? 

maml-checkpoint-{epoch}-batch-no-track.pt : **ours-SO** settings. Omni-VRP w/ fully second order.
maml-fomaml-checkpoint-{epoch}-batch-no-track.pt : **ours** settings. Omni-VRP w/ early stopping second order.
pomo-checkpoint-{epoch}-batch.pt : **POMO** settings. POMO trained in the meta-training way.
reptile-checkpoint-{epoch}-instance.pt : **Meta-POMO** settings. Manchanda et al., 2022 work.

**Comment by RoyalSkye** [comment]
> I just wanna check the specific model of pre-trained weights. is it correct?
> 
> maml-checkpoint-{epoch}-batch-no-track.pt : **ours-SO** settings. Omni-VRP w/ fully second order. maml-fomaml-checkpoint-{epoch}-batch-no-track.pt : **ours** settings. Omni-VRP w/ early stopping second order. pomo-checkpoint-{epoch}-batch.pt : **POMO** settings. POMO trained in the meta-training way. reptile-checkpoint-{epoch}-instance.pt : **Meta-POMO** settings. Manchanda et al., 2022 work.

Exactly.
